export const PsalmAntiphones = [
    'In the law of the Lord they delight day and night.',
    'Serve the Lord with fear; with trembling pay him your homage',
    'Arise, O Lord; Save me, my God.',
    'In peace I will lie down and fall asleep',
    'Give heed to my cry to you, O Lord.',
    'Lord, heal me; my bones are shaking.',
    'God is a just judge, powerful and patient every day.',
    'You put all things under his feet',
    'Arise, O Lord, let human strength not prevail',
    'O Lord, why do you stand a-far off?',
    'The Lord is in his holy temple; the throne of the Lord is in heaven.',
    'O Lord, keep us safe and protect us forever.',
    'I will sing to the Lord who has been bountiful with me.',
    'Jacob will be glad and Israel rejoice',
    'Whoever does not slander with his tongue abides in the tent of God.',
    'Preserve me, O God, for in you I take refuge.',
    'Turn your ear to me, O God, hear my words',
    'The Lord is my rock and my refuge.',
    'The command of the Lord is clear; it gives light to the eyes.',
    'I know the Lord saves his anointed',
    'By your saving help, great is His glory',
    'Stay not far from me, O Lord; trouble is near and there is none to help.',
    'He revives my soul.',
    'The clean of hands and pure of heart shall climb the mountain of the Lord',
    'Let none who hope in you, O Lord, be put to shame.',
    'Your mercy, O Lord, is before my eyes.',
    'The Lord is my light and my salvation',
    'The Lord is my strength and my shield',
    'Bow down before the Lord, majestic in holiness',
    'O Lord, you have lifted up my soul from the grave.',
    'In your justice, set me free, O Lord',
    'You have forgiven the guilt of my sin.',
    'Let all the earth fear the Lord.',
    'When the just cry out, the Lord hears them.',
    'My soul shall rejoice in the Lord, and exult in his salvation.',
    'Your mercy, O Lord, reaches the heavens',
    'Commit your way to the Lord.',
    'O Lord, all my lonliness lies before you.',
    'Take away your scourge from me, O Lord.',
    'Many shall see and fear and trust in the Lord',
    'Heal my soul, O Lord, for I have sinned against you.',
    'My soul is thirsting for the living God',
    'Send forth your light and truth.',
    'You saved us from our foes, therefore we praise your name forever.',
    'My heart overflows with noble words.',
    'The holy place is the dwelling of the most high.',
    'Sing praise to God, our King.',
    'As we have heard, so have we seen in the city of our God.',
    'Why should I fear in evil days?',
    'The God of Gods, the Lord, has spoken.',
    'Have mercy on me, O God.',
    'I will thank you, O Lord, for this is your doing.',
    'The Lord brings about the return of his people.',
    'The Lord sustains my soul.',
    'Attend to me and reply, O Lord.',
    'In God I trust; I shall not fear. What can mere flesh do to me?',
    'In you my soul has taken refuge.',
    'Mete out fair judgement to the sons of man.',
    'Awake! Come to me and see!',
    'Give us, O Lord, help against the foe.',
    'You have given me the heritage of those who fear your name.',
    'My soul rests in God alone.',
    'My lips shall sing your praise all my life.',
    'How profound are the depths of the heart?',
    'Blessed is he whom you choose to call and dwell in your courts.',
    'O peoples, bless our God!',
    'Let the peoples praise you, O God, let all the peoples praise you.',
    'The just shall rejoice at the presence of God.',
    'God, seeking hearts, will revive mine',
    'O Lord, make haste to help me!',
    'My God, free me from the hand of the wicked.',
    'Every tribe shall be blessed in him, all nations call him blessed.',
    'How good is God to Israel?',
    'Remember your flock, O Lord.',
    'Your name is near, O Lord.',
    'In Israel, the name of the Lord is great.',
    'What God is as great as our God?',
    'The Lord saves his people from the foe.',
    'Free us and forgive us our sins, O Lord.',
    'Rouse up your might, O Lord, and come to save us!',
    'Sing joyfully to God our strength.',
    'You sat enthroned, an upright judge.',
    'You alone are Most High over all the earth.',
    'Blessed are they who dwell in your house, O Lord.',
    'Let us see, O Lord, your mercy.',
    'Give ear, O Lord, to my prayer.',
    'The Lord loves the gates of Zion.',
    'Let my prayer come into your presence, O Lord.',
    'Justice and right judgment are the pillars of your throne.',
    'Teach us to number our days.',
    'You, O Lord, are my refuge.',
    'It is good to give thanks to the Lord.',
    'The Lord is King.',
    'How long shall the wicked triumph?',
    'Come, let us worship, for the Lord is our God.',
    'Proclaim his salvation day by day.',
    'The Lord is king, let the earth rejoice.',
    'The Lord has shown his deliverace to the nations.',
    'Exalt the Lord our God and bow.',
    'Cry out with Joy to the Lord, all the earth.',
    'O when will you come to me?',
    'Let my cry come to you, O Lord.',
    'Bless the Lord, O my soul.',
    'How many are your works, O Lord?',
    'Let the heart that seeks the Lord rejoice.',
    'Visit me, O Lord, with your saving power.',
    'Thank the Lord for his mercy.',
    'I will praise you, O Lord, among the peoples.',
    'Do not be silent, O God. Loud thanks to the Lord are on my lips.',
    'The Lord, standing at your right, shatters kings in the day of his wrath.',
    'His precepts are sure, standing firm forever and ever.',
    'Who takes great delight in his commandments?',
    'May the name of the Lord be blessed forever more.',
    'We who live will bless the Lord.',
    'To your name, O Lord, give the glory.',
    'The Lord has turned his ear to me.',
    'I will call on the name of the Lord.',
    'Oh praise the Lord, all you nations.',
    'The Lord\'s right hand is exalted',
    'Blessed are those who walk in your law, O Lord.',
    'I have longed for your salvation, O Lord, and your law is my delight.',
    'I call, and the Lord answers me.',
    'From where shall my help come?',
    'Let us go to the house of the Lord.',
    'You who dwell in the heavens, show us your mercy.',
    'Our help is in the name of the Lord.',
    'Do good, O Lord, to the upright in heart.',
    'What great deeds the Lord has worked for us!',
    'If the Lord does not guard us, in vain do our eyes stay awake.',
    'Blessed are all who fear the Lord.',
    'The Lord has destroyed the yolk of the wicked.',
    'Out of the depths I cry to you, O Lord.',
    'O Israel, wait for the Lord.',
    'The Lord swore to David. He will not go back no his word.',
    'Brothers live in unity.',
    'In the night, bless the Lord.',
    'Lord, your name stands forever.',
    'Give thanks to the Lord.',
    'Remember! O Lord!',
    'The Lord is high, yet he looks on the lowly.',
    'O Lord, you search me and know me.',
    'My Lord, my mighty help.',
    'Oh Lord, I call to you.',
    'You, O Lord, are my portion in the land of the living.',
    'O Lord, give an answer!',
    'Blessed be the Lord my God.',
    'Your kingdom, O Lord, is an everlasting kingdom.',
    'I will praise the Lord all my life.',
    'His wisdom can never be measured.',
    'Praise the Lord from the earth.',
    'The Lord crowns the poor with salvation.',
    'Praise the Lord, O praise him!'
]