version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "chalupaul"
github_repo = "fatsonline"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::905590892698:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-gXyYRANuS3YE"
cloudformation_execution_role = "arn:aws:iam::905590892698:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-LLtHXYtBZkNk"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ieemkdx4oibe"
image_repository = ""
region = "us-east-1"
